name=ESSENTIALS Shader
description=A lightweight Minecraft shader with only essential VFX to simulate realistic effects such as shadows, sun rays, etc., to run on integrated GPUs
version=1.0
profile=LOW